FROM python:2-slim
MAINTAINER Jan Dittberner <jan.dittberner@t-systems.com>
LABEL vendor=T-Systems\ Multimedia\ Solutions\ GmbH
LABEL devday.release=0.1

ARG http_proxy
ARG no_proxy

ENV http_proxy ${http_proxy}
ENV https_proxy ${http_proxy}
ENV no_proxy ${no_proxy}
ENV PYTHONUNBUFFERED 1
ENV DEVDAY_PG_DBNAME devday
ENV DEVDAY_PG_HOST db
ENV DEVDAY_PG_PORT 5432
ENV DEVDAY_PG_USER devday

EXPOSE 8000

VOLUME /srv/devday/devday /srv/devday/devday/media /srv/devday/devday/static
WORKDIR /srv/devday
COPY devday/dev_requirements.txt devday/requirements.txt /srv/devday/

RUN apt-get update && \
    apt-get install -y gettext libmagic1 build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    ln -fs /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.py /usr/lib/python2.7/ && \
    pip install --upgrade pip && \
    pip install -r dev_requirements.txt && \
    rm -rf /root/.cache && \
    find /usr/local -type f -name '*.pyc' -delete

WORKDIR /srv/devday/devday

# tail /dev/null to keep container alive
ENTRYPOINT ["python", "manage.py", "runserver", "0.0.0.0:8000"]
