FROM python:2-slim
MAINTAINER Jan Dittberner <jan.dittberner@t-systems.com>
LABEL vendor=T-Systems\ Multimedia\ Solutions\ GmbH
LABEL devday.release=0.1

ARG http_proxy
ARG no_proxy

ENV http_proxy ${http_proxy}
ENV https_proxy ${http_proxy}
ENV no_proxy ${no_proxy}
ENV PYTHONUNBUFFERED 1
ENV DEVDAY_PG_DBNAME devday
ENV DEVDAY_PG_HOST db
ENV DEVDAY_PG_PORT 5432
ENV DEVDAY_PG_USER devday
ENV REQUESTS_CA_BUNDLE /etc/ssl/certs/ca-certificates.crt

EXPOSE 7000

VOLUME /srv/devday/media /srv/devday/static /srv/devday/logs
COPY devday docker/app/start-application.sh docker/app/uwsgi.ini docker/app/devday.wsgi /srv/devday/
COPY docker/app/vault.crt /usr/local/share/ca-certificates/

WORKDIR /srv/devday

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
        uwsgi-plugin-python uwsgi libmagic1 gettext-base libpq5 \
        gettext build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    ln -fs /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.py \
           /usr/lib/python2.7/ && \
    update-ca-certificates && \
    pip install --upgrade pip && \
    pip install -r requirements.txt && \
    rm -rf /root/.cache && \
    find /usr/local -type f -name '*.pyc' -delete && \
    python manage.py compilemessages && \
    apt-get autoremove --purge -y gettext build-essential

CMD /srv/devday/start-application.sh
