FROM python:3.6-alpine
MAINTAINER Jan Dittberner <jan.dittberner@t-systems.com>
LABEL vendor="T-Systems Multimedia Solutions GmbH"
LABEL devday.release=0.1

ARG http_proxy
ARG no_proxy

ENV \
  http_proxy=${http_proxy} \
  https_proxy=${http_proxy} \
  no_proxy=${no_proxy} \
  PYTHONUNBUFFERED=1 \
  PYTHONFAULTHANDLER=1 \
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  PIPENV_HIDE_EMOJIS=true \
  PIPENV_COLORBLIND=true \
  PIPENV_NOSPIN=true \
  PIPENV_DOTENV_LOCATION=config/.env \
  DEVDAY_PG_DBNAME=devday \
  DEVDAY_PG_HOST=db \
  DEVDAY_PG_PORT=5432 \
  DEVDAY_PG_USER=devday \
  REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

VOLUME /srv/devday/media /srv/devday/static /srv/devday/logs

WORKDIR /srv/devday

RUN apk --no-cache add \
    ca-certificates \
    dumb-init \
    gettext \
    jpeg \
    libmagic \
    libpng \
    libpq \
    libxml2 \
    libxslt \
    python3

COPY Pipfile Pipfile.lock /srv/devday/

RUN apk --no-cache add \
    bash \
    build-base \
    curl \
    gcc \
    git \
    jpeg-dev \
    libffi-dev \
    libpng-dev \
    libxml2-dev \
    libxslt-dev \
    linux-headers \
    musl-dev \
    postgresql-dev \
    zlib-dev \
  && pip install pipenv

RUN pipenv install --system --deploy --ignore-pipfile --dev --verbose

EXPOSE 8000

VOLUME /srv/devday

ENTRYPOINT ["dumb-init", "python", "manage.py", "runserver", "0.0.0.0:8000"]
