FROM python:3.6-alpine
MAINTAINER Jan Dittberner <jan.dittberner@t-systems.com>
LABEL vendor=T-Systems\ Multimedia\ Solutions\ GmbH
LABEL devday.release=0.1

ARG http_proxy
ARG no_proxy

ENV \
  http_proxy=${http_proxy} \
  https_proxy=${http_proxy} \
  no_proxy=${no_proxy} \
  PYTHONUNBUFFERED=1 \
  PYTHONFAULTHANDLER=1 \
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  PIPENV_HIDE_EMOJIS=true \
  PIPENV_COLORBLIND=true \
  PIPENV_NOSPIN=true \
  PIPENV_DOTENV_LOCATION=config/.env \
  DEVDAY_PG_DBNAME=devday \
  DEVDAY_PG_HOST=db \
  DEVDAY_PG_PORT=5432 \
  DEVDAY_PG_USER=devday

EXPOSE 8000

RUN apk --no-cache add \
  bash \
  build-base \
  curl \
  gcc \
  gettext \
  git \
  libffi-dev \
  linux-headers \
  musl-dev \
  zlib-dev \
  postgresql-dev \
  jpeg-dev
RUN pip install pipenv

VOLUME /srv/devday /srv/devday/devday/media /srv/devday/devday/static
WORKDIR /srv/devday
COPY Pipfile Pipfile.lock /srv/devday/

RUN pipenv install --system --deploy --ignore-pipfile --dev

WORKDIR /srv/devday/devday

ENTRYPOINT ["python", "manage.py", "runserver", "0.0.0.0:8000"]
