# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='shirt_size',
        ),
    ]
