# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-22 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0002_remove_attendee_shirt_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='contact_permission_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='organization',
            field=models.CharField(blank=True, max_length=128, verbose_name='company or institution'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='position',
            field=models.CharField(blank=True, max_length=128, verbose_name='job or study subject'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='source',
            field=models.TextField(blank=True, help_text='How have you become aware of Dev Day?', verbose_name='contact source'),
        ),
        migrations.AddField(
            model_name='devdayuser',
            name='contact_permission_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='devdayuser',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=64, verbose_name='twitter handle'),
        ),
        migrations.AlterField(
            model_name='devdayuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site.', verbose_name='staff status'),
        ),
    ]
