# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-04 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0003_auto_20161222_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='source',
            field=models.TextField(blank=True, help_text='How have you become aware of Dev Day 2017?', verbose_name='source'),
        ),
    ]
