# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-17 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_squashed_0002_auto_20170917_1155'),
        ('attendee', '0004_auto_20170104_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event', verbose_name='Event'),
        ),
    ]
