# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-13 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_squashed_0002_auto_20170917_1155'),
        ('attendee', '0004_auto_20170104_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='event',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.Event', verbose_name='Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devdayuser',
            name='organization',
            field=models.CharField(blank=True, max_length=128, verbose_name='company or institution'),
        ),
        migrations.AddField(
            model_name='devdayuser',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='devdayuser',
            name='position',
            field=models.CharField(blank=True, max_length=128, verbose_name='job or study subject'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='source',
            field=models.TextField(blank=True, help_text='How have you become aware of this event?', verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='attendee.DevDayUser'),
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='contact_permission_date',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='position',
        ),
        migrations.AlterUniqueTogether(
            name='attendee',
            unique_together=set([('user', 'event')]),
        ),
    ]
