# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-07 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0005_auto_20171013_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devdayuser',
            name='contact_permission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
