# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-17 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0005_attendee_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='attendee.DevDayUser'),
        ),
        migrations.AlterUniqueTogether(
            name='attendee',
            unique_together=set([('user', 'event')]),
        ),
    ]
