# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-10 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0006_auto_20171207_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devdayuser',
            name='contact_permission_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='contact permission date'),
        ),
    ]
