# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-18 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0006_auto_20170917_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='devdayuser',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Phone'),
        ),
    ]
