# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-10 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0007_auto_20180410_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='checked_in',
            field=models.DateTimeField(blank=True, help_text='Date and time the attendee checked in', null=True, verbose_name='Checked-In'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='checkin_code',
            field=models.CharField(help_text='Code to check in attendee manually', max_length=30, null=True, unique=True, verbose_name='Check-In Code'),
        ),
    ]
