# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-02 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0007_devdayuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.Event', verbose_name='Event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='attendee.DevDayUser'),
        ),
    ]
