# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0008_add_checkin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devdayuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='devdayuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='devdayuser',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='devdayuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='devdayuser',
            name='position',
        ),
        migrations.RemoveField(
            model_name='devdayuser',
            name='twitter_handle',
        ),
    ]
