# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-04 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0008_auto_20171002_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendee', to='attendee.DevDayUser'),
        ),
    ]
