# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("attendee", "0010_add_attendee_event_feedback")]

    operations = [
        migrations.AddField(
            model_name="attendee",
            name="raffle",
            field=models.BooleanField(
                default=False,
                help_text="Take part in the raffle",
                verbose_name="raffle",
            ),
        )
    ]
