# Generated by Django 2.2.9 on 2020-01-28 09:28

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendee", "0011_add_raffle_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendeeeventfeedback",
            name="attendee",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"event__published": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="attendee.Attendee",
                verbose_name="Attendee",
            ),
        ),
        migrations.AlterField(
            model_name="attendeeeventfeedback",
            name="event",
            field=models.ForeignKey(
                limit_choices_to={"published": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="event.Event",
                verbose_name="Event",
            ),
        ),
        migrations.CreateModel(
            name="BadgeData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="How would you like to be named",
                        max_length=50,
                        verbose_name="Title",
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True,
                        help_text="optional contact information (i.e. a Twitter handle)",
                        max_length=50,
                        verbose_name="Contact",
                    ),
                ),
                (
                    "topics",
                    models.TextField(
                        blank=True,
                        help_text="Topics you would like to talk about",
                        max_length=150,
                        verbose_name="Topics",
                    ),
                ),
                (
                    "attendee",
                    models.OneToOneField(
                        blank=True,
                        limit_choices_to={"event__published": True},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendee.Attendee",
                        verbose_name="Attendee",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": "Badge data",
                "verbose_name_plural": "Badge data",
            },
        ),
    ]
