# Generated by Django 2.2.24 on 2021-11-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0047_use_links_for_talk_media_drop_old_fields'),
        ('attendee', '0012_add_badge_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='devdayuser',
            name='favourite_talks',
            field=models.ManyToManyField(to='talk.Talk'),
        ),
    ]
