# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videopermission', models.BooleanField(verbose_name='Video permitted')),
                ('shortbio', models.TextField(verbose_name='Short biography')),
                ('portrait', models.ImageField(upload_to=b'', verbose_name='Speaker image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendee.Attendee')),
            ],
            options={
                'verbose_name': 'Speaker',
                'verbose_name_plural': 'Speakers',
            },
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Session title')),
                ('abstract', models.TextField(verbose_name='Abstract')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talk.Speaker')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
        ),
    ]
