# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='portrait',
            field=models.ImageField(upload_to='speakers', verbose_name='Speaker image'),
        ),
    ]
