# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-22 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
    ]
