# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-27 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0002_auto_20160802_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to='attendee.Attendee'),
        ),
    ]
