# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0002_auto_20160922_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='shirt_size',
            field=models.PositiveSmallIntegerField(choices=[(1, 'XS'), (2, 'S'), (3, 'M'), (4, 'L'), (5, 'XL'), (6, 'XXL'), (7, 'XXXL')], default=4, verbose_name='T-shirt size'),
            preserve_default=False,
        ),
    ]
