# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0003_speaker_shirt_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='speaker_thumbs', verbose_name='Speaker image thumbnail'),
        ),
    ]
