# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-04 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0004_auto_20170104_1522'),
        ('talk', '0004_speaker_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('comment', models.TextField()),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendee.DevDayUser')),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talk.Talk')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talk.Talk')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendee.DevDayUser')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('voter', 'score')]),
        ),
    ]
