# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-04 14:55
from __future__ import unicode_literals

from django.contrib.auth.management import create_permissions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0002_alter_permission_name_max_length'),
        ('talk', '0005_auto_20170104_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkcomment',
            name='is_visible',
            field=models.BooleanField(default=False,
                                      help_text='Indicates whether the comment is visible to the speaker.'),
        ),
    ]
