# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-06 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0006_auto_20170104_1555'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('voter', 'talk')]),
        ),
    ]
