# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-04 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0010_auto_20170304_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['name'], 'verbose_name': 'Time slot', 'verbose_name_plural': 'Time slots'},
        ),
        migrations.AddField(
            model_name='room',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
