# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-14 19:21
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0012_auto_20170304_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkslot',
            name='talk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talkslot', to='talk.Talk'),
        ),
    ]
