# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-14 19:32
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0013_auto_20170314_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['start_time', 'end_time', 'name'], 'verbose_name': 'Time slot', 'verbose_name_plural': 'Time slots'},
        ),
        migrations.AddField(
            model_name='timeslot',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
