# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-14 19:48
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0014_auto_20170314_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkslot',
            name='talk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='talk.Talk'),
        ),
    ]
