# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-15 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0015_auto_20170314_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='text_body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
