# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-07 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0021_remove_talk_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='event',
        ),
    ]
