# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-07 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0022_remove_speaker_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set([('name', 'event')]),
        ),
    ]
