# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-27 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0023_auto_20180207_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkmedia',
            name='codelink',
            field=models.CharField(blank=True, max_length=255, verbose_name='Source code'),
        ),
    ]
