# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0026_timeslot_unique_name_and_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('duration', models.PositiveSmallIntegerField(
                    default=60, verbose_name='Duration')),
            ],
        ),
        migrations.AddField(
            model_name='talk',
            name='talkformat',
            field=models.ManyToManyField(to='talk.TalkFormat',
                                         verbose_name='Talk Formats'),
        ),
    ]
