# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-01 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('talk', '0027_talkformats'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='slug',
            field=models.SlugField(max_length=255, default='', verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
