# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-13 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def assign_new_speaker_models(apps, schema_manager):
    Talk = apps.get_model('talk', 'Talk')
    Speaker = apps.get_model('speaker', 'Speaker')
    PublishedSpeaker = apps.get_model('speaker', 'PublishedSpeaker')

    for talk in Talk.objects.all():
        speaker = talk.speaker

        talk.draft_speaker = Speaker.objects.get(user=speaker.user.user)
        talk.published_speaker = PublishedSpeaker.get(speaker=talk.draft_speaker)
        talk.event = speaker.user.event
        talk.submission_timestamp = talk.event.start_time
        talk.save()


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0002_migrate_speakers_from_talk_app'),
        ('event', '0005_auto_20181010_2051'),
        ('talk', '0030_fill_session_slugs_from_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='draft_speaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='speaker.Speaker', verbose_name='Speaker (draft)'),
        ),
        migrations.AddField(
            model_name='talk',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='talk',
            name='published_speaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='speaker.PublishedSpeaker', verbose_name='Speaker (public)'),
        ),
        migrations.AddField(
            model_name='talk',
            name='submission_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(
            assign_new_speaker_models
        ),
    ]
