# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-13 15:38
from __future__ import unicode_literals

from django.db import migrations


def assign_new_speaker_models(apps, schema_manager):
    Talk = apps.get_model('talk', 'Talk')
    Speaker = apps.get_model('speaker', 'Speaker')
    PublishedSpeaker = apps.get_model('speaker', 'PublishedSpeaker')

    for talk in Talk.objects.all():
        speaker = talk.speaker

        talk.draft_speaker = Speaker.objects.get(user=speaker.user.user)
        talk.published_speaker = PublishedSpeaker.objects.get(
            speaker=talk.draft_speaker)
        talk.event = speaker.user.event
        talk.submission_timestamp = talk.event.start_time
        talk.save()


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0002_migrate_speakers_from_talk_app'),
        ('event', '0005_auto_20181010_2051'),
        ('talk', '0031_add_talk_fields_for_speakers_and_events'),
    ]

    operations = [
        migrations.RunPython(
            assign_new_speaker_models
        ),
    ]
