# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-13 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0032_use_new_speaker_models_for_talks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='speaker',
        ),
    ]
