# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0032_remove_talk_speaker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='user',
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
    ]
