# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 11:54
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('talk', '0033_remove_talk_speaker'),
        ('event', '0006_auto_20181016_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='user',
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
        migrations.AlterModelOptions(
            name='room',
            options={
                'ordering': ['event', 'priority', 'name'],
                'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('name', 'event')},
        ),
        migrations.AlterField(
            model_name='talk',
            name='draft_speaker',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='speaker.Speaker', verbose_name='Speaker (draft)'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='event',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='event.Event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='published_speaker',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='speaker.PublishedSpeaker',
                verbose_name='Speaker (public)'),
        ),
    ]
