# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20181016_0051'),
        ('talk', '0033_auto_20181014_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['event', 'priority', 'name'], 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set([('name', 'event')]),
        ),
    ]
