# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0034_auto_20181016_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='draft_speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='speaker.Speaker', verbose_name='Speaker (draft)'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='published_speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='speaker.PublishedSpeaker', verbose_name='Speaker (public)'),
        ),
    ]
