# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-15 13:48
from __future__ import unicode_literals

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('talk', '0035_add_event_specific_rooms_for_talks'),
        ('attendee', '0009_auto_20181020_0802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talkformat',
            options={'ordering': ['duration', 'name'],
                     'verbose_name': 'Talk Format',
                     'verbose_name_plural': 'Talk Format'},
        ),
        migrations.AddField(
            model_name='talkslot',
            name='spots',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Maximum number of attendees for this talk',
                verbose_name='Spots'),
        ),
        migrations.CreateModel(
            name='SessionReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='modified')),
                ('is_confirmed',
                 models.BooleanField(default=False, verbose_name='Confirmed')),
                ('attendee',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='attendee.Attendee',
                                   verbose_name='Attendee')),
                ('talk_slot',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='talk.TalkSlot', verbose_name='Talk')),
            ],
            options={
                'verbose_name': 'Session reservation',
                'verbose_name_plural': 'Session reservations',
            },
        ),
        migrations.AlterUniqueTogether(
            name='sessionreservation',
            unique_together={('attendee', 'talk_slot')},
        ),
    ]
