# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 16:37
from __future__ import unicode_literals

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attendee', '0009_auto_20181020_0802'),
        ('talk', '0036_add_session_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeeVote',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='modified')),
                ('score', models.PositiveSmallIntegerField()),
                ('attendee', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='attendee.Attendee', verbose_name='Attendee')),
                ('talk', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='talk.Talk', verbose_name='Talk')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='attendeevote',
            unique_together={('attendee', 'talk')},
        ),
        migrations.CreateModel(
            name='AttendeeFeedback',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False,
                    verbose_name='modified')),
                ('score', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(
                    blank=True, verbose_name='Comment')),
                ('attendee', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='attendee.Attendee', verbose_name='Attendee')),
                ('talk', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='talk.Talk', verbose_name='Talk')),
            ],
            options={
                'verbose_name': 'Attendee feedback',
                'verbose_name_plural': 'Attendee feedback',
            },
        ),
        migrations.AlterModelOptions(
            name='attendeevote',
            options={
                'verbose_name': 'Attendee vote',
                'verbose_name_plural': 'Attendee votes'},
        ),
        migrations.AlterUniqueTogether(
            name='attendeefeedback',
            unique_together={('attendee', 'talk')},
        ),
    ]
