# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 10:10
from __future__ import unicode_literals

from django.db import migrations
import psqlextra.manager.manager


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0037_attendee_participation_models'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='attendeevote',
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
