# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-07 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("talk", "0039_add_is_waiting_to_sessionreservation")]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="block",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Block"),
        )
    ]
