# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("attendee", "0009_auto_20181020_0802"),
        ("event", "0007_event_voting_open"),
        ("talk", "0041_drop_unique_constraint_on_talkslot"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendeeEventFeedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "overall_score",
                    models.PositiveSmallIntegerField(verbose_name="Event score"),
                ),
                (
                    "organisation_score",
                    models.PositiveSmallIntegerField(verbose_name="Organisation score"),
                ),
                (
                    "session_score",
                    models.PositiveSmallIntegerField(verbose_name="Session score"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Comment")),
                (
                    "attendee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="attendee.Attendee",
                        verbose_name="Attendee",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.Event",
                        verbose_name="Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendee event feedback",
                "verbose_name_plural": "Attendee event feedback",
            },
        ),
        migrations.AlterField(
            model_name="attendeefeedback",
            name="attendee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="attendee.Attendee",
                verbose_name="Attendee",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendeeeventfeedback", unique_together={("attendee", "event")}
        ),
    ]
