# Generated by Django 2.2.10 on 2020-03-10 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0042_delete_attendee_feedback_with_attendee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeefeedback',
            name='attendee',
            field=models.ForeignKey(blank=True, limit_choices_to={'event__published': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendee.Attendee', verbose_name='Attendee'),
        ),
        migrations.AlterField(
            model_name='attendeefeedback',
            name='talk',
            field=models.ForeignKey(limit_choices_to={'track__is_null': False}, on_delete=django.db.models.deletion.CASCADE, to='talk.Talk', verbose_name='Talk'),
        ),
        migrations.AlterField(
            model_name='attendeevote',
            name='attendee',
            field=models.ForeignKey(limit_choices_to={'event__published': True}, on_delete=django.db.models.deletion.CASCADE, to='attendee.Attendee', verbose_name='Attendee'),
        ),
        migrations.AlterField(
            model_name='attendeevote',
            name='talk',
            field=models.ForeignKey(limit_choices_to={'track__is_null': False}, on_delete=django.db.models.deletion.CASCADE, to='talk.Talk', verbose_name='Talk'),
        ),
        migrations.AlterField(
            model_name='sessionreservation',
            name='attendee',
            field=models.ForeignKey(limit_choices_to={'event__published': True}, on_delete=django.db.models.deletion.CASCADE, to='attendee.Attendee', verbose_name='Attendee'),
        ),
        migrations.AlterField(
            model_name='sessionreservation',
            name='talk',
            field=models.ForeignKey(limit_choices_to={'spots__gt': 0}, on_delete=django.db.models.deletion.CASCADE, to='talk.Talk', verbose_name='Talk'),
        ),
    ]
