# Generated by Django 2.2.10 on 2020-03-10 20:10

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


def migrate_speakers(apps, schema_editor):
    Talk = apps.get_model("talk", "Talk")
    TalkPublishedSpeaker = apps.get_model("talk", "TalkPublishedSpeaker")
    TalkDraftSpeaker = apps.get_model("talk", "TalkDraftSpeaker")

    db_alias = schema_editor.connection.alias
    for talk in Talk.objects.using(db_alias).all():
        if talk.published_speaker is not None:
            TalkPublishedSpeaker.objects.using(db_alias).create(
                published_speaker_id=talk.published_speaker.id, talk_id=talk.id, order=1
            )
        if talk.draft_speaker is not None:
            TalkDraftSpeaker.objects.using(db_alias).create(
                draft_speaker_id=talk.draft_speaker.id, talk_id=talk.id, order=1
            )


class Migration(migrations.Migration):

    dependencies = [
        ("speaker", "0003_auto_20181019_0948"),
        ("talk", "0043_auto_20200310_1737"),
    ]

    operations = [
        migrations.CreateModel(
            name="TalkPublishedSpeaker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "published_speaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="speaker.PublishedSpeaker",
                        verbose_name="Published speaker",
                    ),
                ),
                (
                    "talk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="talk.Talk",
                        verbose_name="Talk",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "verbose_name": "Talk published speaker",
                "verbose_name_plural": "Talk published speakers",
                "unique_together": {("talk", "published_speaker")},
            },
        ),
        migrations.CreateModel(
            name="TalkDraftSpeaker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "draft_speaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="speaker.Speaker",
                        verbose_name="Speaker",
                    ),
                ),
                (
                    "talk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="talk.Talk",
                        verbose_name="Talk",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "verbose_name": "Talk draft speaker",
                "verbose_name_plural": "Talk draft speakers",
                "unique_together": {("talk", "draft_speaker")},
            },
        ),
        migrations.RunPython(migrate_speakers),
        migrations.RemoveField(model_name="talk", name="draft_speaker"),
        migrations.RemoveField(model_name="talk", name="published_speaker"),
        migrations.AddField(
            model_name="talk",
            name="draft_speakers",
            field=models.ManyToManyField(
                blank=True,
                through="talk.TalkDraftSpeaker",
                to="speaker.Speaker",
                verbose_name="Speaker (draft)",
            ),
        ),
        migrations.AddField(
            model_name="talk",
            name="published_speakers",
            field=models.ManyToManyField(
                blank=True,
                through="talk.TalkPublishedSpeaker",
                to="speaker.PublishedSpeaker",
                verbose_name="Speaker (public)",
            ),
        ),
    ]
