FROM node:lts
MAINTAINER Jan Dittberner <jan.dittberner@t-systems.com>
LABEL vendor=T-Systems\ Multimedia\ Solutions\ GmbH

VOLUME /app /app/frontend/node_modules

WORKDIR /app/frontend

ENV PATH=/app/frontend/node_modules/.bin:$PATH

CMD /bin/bash
