FROM node:lts
MAINTAINER Jan Dittberner <jan.dittberner@telekom.de>
LABEL vendor=Deutsche\ Telekom\ MMS\ GmbH

VOLUME /app /app/frontend/node_modules

WORKDIR /app/frontend

ENV PATH=/app/frontend/node_modules/.bin:$PATH

CMD /bin/bash
