version: '3'
services:
  db:
    image: postgres:12
    ports:
      - "15432:5432"
    env_file:
      dev-env-db
    read_only: true
    volumes:
      - "pg_data:/var/lib/postgresql/data"
      - "/var/run/postgresql"
      - "./docker/db/dev/init-user-db.sql:/docker-entrypoint-initdb.d/init-user-db.sql:ro"
    cap_drop:
      - ALL
    cap_add:
      - CAP_CHOWN
      - CAP_DAC_READ_SEARCH
      - CAP_FOWNER
      - CAP_SETGID
      - CAP_SETUID
  app:
    image: devdaydresden/devday_website_app:latest_dev
    build:
      context: .
      dockerfile: app-dev.Dockerfile
      args:
        http_proxy: ${http_proxy}
        no_proxy: ${no_proxy},vault
    read_only: true
    ports:
      - "8000:8000"
    environment:
      DEVDAY_PG_DBNAME: devday
      DEVDAY_PG_HOST: db
      DEVDAY_PG_PORT: 5432
      DEVDAY_PG_USER: devday
      DJANGO_SETTINGS_MODULE: devday.settings
    env_file:
      dev-env
    volumes:
      - "./devday:/app"
      - "devday_logs:/app/logs"
      - "devday_media:/app/media"
      - "devday_static:/app/static"
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    cap_add:
      - CAP_DAC_OVERRIDE
    depends_on:
      - db

volumes:
  devday_logs:
  devday_media:
  devday_static:
  pg_data:
