# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0006_auto_20181016_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsoringPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.PositiveSmallIntegerField(choices=[(1, 'Gold'), (2, 'Silver'), (3, 'Bronze')], verbose_name='Package')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Sponsoring Package',
                'verbose_name_plural': 'Sponsoring Packages',
            },
        ),
        migrations.CreateModel(
            name='SponsoringPackageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_header', models.BooleanField(default=False, verbose_name='Header')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsoring.SponsoringPackage', verbose_name='Package')),
            ],
            options={
                'verbose_name': 'Sponsoring Package Item',
                'verbose_name_plural': 'Sponsoring Package Items',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='sponsoringpackage',
            unique_together=set([('event', 'package_type')]),
        ),
    ]
