# Generated by Django 2.2.10 on 2020-03-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsoring', '0003_change_meta_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsoringpackageitem',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
