# Generated by Django 2.2.28 on 2022-12-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsoring', '0004_auto_20200310_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsoringpackage',
            name='package_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Platinum'), (2, 'Gold'), (3, 'Silver')], verbose_name='Package'),
        ),
    ]
