# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-18 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.CharField(max_length=64)),
                ('user_profile_image_url', models.CharField(blank=True, max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('user_screen_name', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField()),
                ('show_on_site', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='setting name')),
                ('value', models.TextField(verbose_name='setting value')),
            ],
            options={
                'verbose_name': 'Twitter setting',
                'verbose_name_plural': 'Twitter settings',
            },
        ),
    ]
