# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-18 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterfeed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='id_str',
        ),
        migrations.AddField(
            model_name='tweet',
            name='twitter_id',
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
