# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-29 12:16
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('twitterfeed', '0003_auto_20170129_1110'), ('twitterfeed', '0004_auto_20170129_1129'), ('twitterfeed', '0005_auto_20170129_1231'), ('twitterfeed', '0006_auto_20170129_1243')]

    dependencies = [
        ('twitterfeed', '0002_auto_20170118_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile_image_url', models.CharField(max_length=255, unique=True)),
                ('image_data', models.ImageField(height_field='image_height', upload_to='twitter_profile', width_field='image_width')),
                ('image_height', models.SmallIntegerField(default=0)),
                ('image_width', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='user_profile_image_url',
        ),
        migrations.AddField(
            model_name='tweet',
            name='user_profile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='twitterfeed.TwitterProfileImage'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='tweet',
            name='entities',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='plain_text',
            field=models.CharField(default='', max_length=160),
            preserve_default=False,
        ),
    ]
