# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-29 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterfeed', '0003_auto_20170129_1110_squashed_0006_auto_20170129_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'verbose_name': 'Tweet', 'verbose_name_plural': 'Tweets'},
        ),
        migrations.AlterModelOptions(
            name='twitterprofileimage',
            options={'verbose_name': 'Twitter profile image', 'verbose_name_plural': 'Twitter profile images'},
        ),
        migrations.AlterField(
            model_name='tweet',
            name='show_on_site',
            field=models.BooleanField(default=False, verbose_name='show on site'),
        ),
    ]
