# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-13 16:25
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.timezone import datetime


def create_devday_17_fwd(apps, schema_manager):
    Event = apps.get_model("event", "Event")
    event = Event(id=1, title='devdata.17', slug='devdata17',
                  description='Dev Data.17 am 4.4. in Dresden', location='Dresden',
                  full_day=False, start_time=datetime(2017, 4, 4, 13, 0),
                  end_time=datetime(2017, 4, 4, 20, 0))
    event.save()


def create_devday_17_rev(apps, schema_manager):
    Event = apps.get_model("event", "Event")
    Event.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Event title')),
                ('slug', models.SlugField(unique=True, verbose_name='Short name for URLs')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('location', models.TextField(blank=True, verbose_name='Location')),
                ('full_day', models.BooleanField(default=False, verbose_name='Full day event')),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('end_time', models.DateTimeField(verbose_name='End time')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.RunPython(create_devday_17_fwd, create_devday_17_rev),
    ]
