# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-17 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('event', '0001_initial'), ('event', '0002_auto_20170917_1155')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Event title')),
                ('slug', models.SlugField(unique=True, verbose_name='Short name for URLs')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('location', models.TextField(blank=True, verbose_name='Location')),
                ('full_day', models.BooleanField(default=False, verbose_name='Full day event')),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('end_time', models.DateTimeField(verbose_name='End time')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
