# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-27 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_open',
            field=models.BooleanField(default=False, verbose_name='People can register as attendees'),
        ),
        migrations.AddField(
            model_name='event',
            name='submission_open',
            field=models.BooleanField(default=False, verbose_name='People can register as speakers'),
        ),
    ]
