# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_registration_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sessions_published',
            field=models.BooleanField(default=True,
                                      verbose_name='Grid Published'),
        ),
    ]
