# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0027_talkformats'),
        ('event', '0002_registration_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='talkformat',
            field=models.ManyToManyField(to='talk.TalkFormat',
                                         verbose_name='Talk Formats'),
        ),
    ]
