# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 20:30
from __future__ import unicode_literals

from django.core.management.color import no_style
from django.db import DEFAULT_DB_ALIAS, connections, migrations, models


def create_dflt_format_fwd(apps, schema_manager):
    Event = apps.get_model("event", "Event")
    Talk = apps.get_model("talk", "Talk")
    TalkFormat = apps.get_model("talk", "TalkFormat")

    talkformat = TalkFormat.objects.create(id=1, name='Vortrag', duration=60)
    sequence_sql = connections[DEFAULT_DB_ALIAS].ops. \
        sequence_reset_sql(no_style(), [TalkFormat])
    if sequence_sql:
        with connections[DEFAULT_DB_ALIAS].cursor() as cursor:
            for command in sequence_sql:
                cursor.execute(command)

    talkformat.event_set.add(*Event.objects.all())
    talkformat.talk_set.add(*Talk.objects.all())


def create_dflt_format_rev(apps, schema_manager):
    TalkFormat = apps.get_model("talk", "TalkFormat")
    TalkFormat.objects.filter(id=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0027_talkformats'),
        ('event', '0003_event_sessions_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='talkformat',
            field=models.ManyToManyField(to='talk.TalkFormat',
                                         verbose_name='Talk Formats'),
        ),
        migrations.RunPython(create_dflt_format_fwd, create_dflt_format_rev),
    ]
