# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-10 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_talkformat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_open',
            field=models.BooleanField(default=False, verbose_name='Registration Open'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sessions_published',
            field=models.BooleanField(default=False, verbose_name='Grid Published'),
        ),
        migrations.AlterField(
            model_name='event',
            name='submission_open',
            field=models.BooleanField(default=False, verbose_name='Submission Open'),
        ),
    ]
