# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-08 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20181016_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='voting_open',
            field=models.BooleanField(default=False, help_text='Attendees can vote for their preferred sessions', verbose_name='Voting Open'),
        ),
    ]
