# Generated by Django 2.2.11 on 2020-05-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_voting_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='online_event',
            field=models.BooleanField(default=False, verbose_name='Online Event'),
        ),
    ]
