# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 09:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0002_migrate_speakers_from_talk_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to=settings.AUTH_USER_MODEL),
        ),
    ]
