#!/bin/bash
set -e

# Avoid  warning: smtputf8_enable is true, but EAI support is not compiled in
postconf -e smtputf8_enable=no
postconf -e inet_interfaces=all
postconf -e inet_protocols=ipv4
postconf -e mynetworks_style=subnet

# Do we want to modify the config first with the script?
# shellcheck disable=SC1091
[ -f /etc/service/postfix/run.config ] && source /etc/service/postfix/run.config

if [[ ! -z "$MAILNAME" ]]; then
    echo "$MAILNAME" > /etc/mailname
    postconf -e myorigin="/etc/mailname"
    postconf -e smtp_always_send_ehlo=yes
    postconf -e smtp_helo_name=$MAILNAME
fi

if [[ ! -z "$POSTFIX_ROOT_ALIAS" ]]; then
    if [[ -f /etc/aliases ]]; then
        sed -i '/^root:/d' /etc/aliases
    fi
    echo "root: $POSTFIX_ROOT_ALIAS" >> /etc/aliases
    newaliases
fi

if [[ ! -z "$POSTFIX_RELAY_HOST" ]]; then
    # setup the relay
    postconf -e relayhost=$POSTFIX_RELAY_HOST
fi

if [ -x /usr/libexec/postfix/master ]; then
    POSTFIX_MASTER=/usr/libexec/postfix/master
else
    POSTFIX_MASTER=/usr/lib/postfix/master
fi
$POSTFIX_MASTER -c /etc/postfix -d 2>&1
tail -F /var/log/mail.log
