---
name: Docker Development CI

# Controls when the workflow will run
on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # build the production Docker image using information from
  # https://github.com/marketplace/actions/build-and-push-docker-images
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          tags: devday_website_app:latest_dev
          file: app-dev.Dockerfile
      -
        name: setup PostgreSQL database
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '12'
          postgresql init scripts: docker/db/dev
      -
        name: run tests
        uses: addnab/docker-run-action@v3
        with:
          image: devday_website_app:latest_dev
          run: coverage run --branch manage.py test
          options: >-
            -e DEVDAY_PG_DBNAME=devday
            -e DEVDAY_PG_HOST=db
            -e DEVDAY_PG_PORT=5432
            -e DEVDAY_PG_USER=devday
            -e DJANGO_SETTINGS_MODULE=devday.settings
            -e POSTGRESQL_PASSWORD=devday
            -e SECRET=test_secret
            -e CONFIRMATION_SALT=test_confirmation_salt
            -e "ADMINS=Admin1 <admin1@example.org>, Admin2 <admin2@example.org>"
            -e DEBUG=true
            -v ${{ github.workspace }}:/devday:/app
