name: Docker CI

# Controls when the workflow will run
on:
  push:
    branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # build the production Docker image using information from
  # https://github.com/marketplace/actions/build-and-push-docker-images
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          # usage of image in a Dockerfile: ghcr.io/devdaydresden/devday_website_app:latest
          tags: devdaydresden/devday_website_app:latest
